$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: emailspam-fare-online
model: azureml:emailspam-model@latest
instance_type: Standard_DS2_v2
instance_count: 1
